#8004表示注册到zookeeper服务器的支付服务提供者的端口号
server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment #服务别名----注册zookeeper到注册中心名称
  cloud:
    zookeeper:
      connect-string: 192.168.3.7:2181 #zookeeper Server的地址和端口号


